sort:
  enabled: false

content: |-

  # Standard PowerVS Infrastructure Module Example

  This example illustrates how to use the `power-infrastructure` module. 
  It provisions the following infrastructure
  - Creates a [PowerVS service instance](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-started) with the following network topology <br/>
    (1) 2 private networks, management network and backup network <br/>
    (2) 1 [IBM Cloud connection](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-cloud-connections), with the option to reuse existing IBM Cloud connections <br/>
    (3) The IBM Cloud connections are attached to a [transit gateway](https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-getting-started) <br/>
    (4) Attaches the PowerVS service instance private networks to the IBM Cloud connections <br/>
  - Creates a ssh key

  :warning: For experimentation purposes only.
  For ease of use, this quick start example generates a private/public ssh key pair. The private key generated in this example will be stored unencrypted in your Terraform state file.
  Use of this resource for production deployments is not recommended. Instead, generate a ssh key pair outside of Terraform and pass the public key via the [ssh_public_key input](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/tree/v0.1#input_ssh_public_key)
  
  {{ .Header }}
  ## Prerequisites
  Make sure you installed the Power flavor of version 0.0.19 or higher of Secure Landing Zone VPC with VSIs.

  ## Requirements

    | Name | Version |
    |------|---------|
    | <a name="requirement_terraform"></a> [terraform](#requirement\_terraform) | >=1.1 |
    | <a name="requirement_ibm"></a> [ibm](#requirement\_ibm) | >= 1.43.0 |
    | <a name="requirement_tls"></a> [tls](#requirement\_tls) | 4.0.1 |

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}


  ## Usage

    terraform apply -var-file="input.tfvars"

  ## Note

  For all optional fields, default values (Eg: `null`) are given in variable.tf file. User can configure the same by overwriting with appropriate values.